//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystemSiaProject.WebPages
{


    public partial class ActivityLogPage
    {

        protected global::System.Web.UI.WebControls.GridView gvActivity;
    }
}
