//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystemSiaProject.WebPages
{


    public partial class ProductInformation
    {
        protected global::System.Web.UI.WebControls.Repeater rptBestSelling;
        protected global::System.Web.UI.WebControls.Panel pnlNoProducts;
    }
}
